config/routes.rb
Rails.application.routes.draw do

  root 'books#index'

  get 'books/index'
  get 'authors/index'

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/author.rb
class Author < ActiveRecord::Base
  validates :first_name, :last_name, presence: true
  validates :first_name, uniqueness: { scope: :last_name }

  has_many :books

  def full_name
    "#{first_name.capitalize} #{last_name.capitalize}"
  end
end

app/models/book.rb
class Book < ActiveRecord::Base
  validates :title, :publisher_id, :author_id, presence: true
  validates :title, uniqueness: true

  belongs_to :publisher
  belongs_to :author

  has_many :book_formats
  has_many :book_format_types, through: :book_formats
  has_many :book_reviews

  def self.search query, options: default_options
    books = search_all query.downcase

    return books.sort_by(&:average_rating).reverse! if options[:title_only]

    if options[:book_format_type_id]

      books = books.joins(:book_format_types)
        .where("book_format_types.id = ?", options[:book_format_type_id])

    elsif options[:book_format_physical]

      books = books.joins(:book_format_types)
        .where("book_format_types.physical = true")

    end

    books.sort_by(&:average_rating).reverse!
  end

  def self.search_all query
    joins(:author)
    .where("lower(authors.first_name) = ? OR lower(authors.last_name) = ?
             OR lower(books.title) LIKE ?", query, query, "%#{query}%")
    .uniq!
  end

  def author_name
    author.full_name
  end

  def average_rating
    (ratings_sum / book_reviews.count).round(1)
  end

  def ratings_sum
    self.book_reviews.pluck(:rating).sum
  end

  private
  def self.default_options
    {title_only: false}
  end

end

app/models/book_format.rb
class BookFormat < ActiveRecord::Base
  validates :book_id, :book_format_type_id, presence: true

  belongs_to :book
  belongs_to :book_format_type
end

app/models/book_format_type.rb
class BookFormatType < ActiveRecord::Base
  validates :name, presence: true

  has_many :book_formats
  has_many :books, through: :book_format_types
end

app/models/book_review.rb
class BookReview < ActiveRecord::Base
  validates :book_id, :rating, presence: true

  belongs_to :book
end

app/models/publisher.rb
class Publisher < ActiveRecord::Base
  validates :name, presence: true, uniqueness: true

  has_many :books
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  def index
    @authors = Author.all.sort_by(&:last_name)

    respond_to do |format|
      format.html
      format.json {render json: @authors}
      format.xml  {render xml: @authors}
    end
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def index
    @books = Book.all.sort_by(&:average_rating).reverse!

    respond_to do |format|
      format.html
      format.json {render json: @books}
      format.xml  {render xml: @books}
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/authors/_author.html.erb
<div class="panel panel-default">
  <div class="panel-body">
    <h4><%= author.full_name %></h4>
  </div>
</div>

app/views/authors/index.html.erb
<% @authors.each do |author| %>
  <%= render partial: 'author', locals: {author: author}%>
<% end %>

app/views/books/_book.html.erb
<div class="panel panel-default">
  <div class="panel-body">
    <h4><%= book.title.capitalize %>
    <% book.average_rating.to_i.times do %>
      <span class="glyphicon glyphicon-star" aria-hidden="true"></span>
    <% end %> </h4>
    <strong>Author: </strong>
    <%= book.author_name %></br>
    <strong>Publisher: </strong>
    Publisher <%= book.publisher.name %></br>
  </div>
</div>

app/views/books/index.html.erb
</br>
<form>
  <fieldset class="form-group">
    <label for="exampleInputEmail1">Search</label>
    <input type="email" class="form-control" id="book-search" placeholder="catcher in the, Jerome">
  </fieldset>
</form>
<% @books.each do |book| %>
  <%= render partial: 'book', locals: { book: book } %>
<% end %>

app/views/layouts/_nav.html.erb
<ul class="nav nav-tabs">
  <li class="nav-item"><%= link_to 'Books', root_path, class: 'nav-link active' %></li>
  <li class="nav-item"><%= link_to 'Author', authors_index_path, class: 'nav-link active' %></li>
  <li class="nav-item"><%= link_to 'Publisher', '', class: 'nav-link active' %></li>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bookstore</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class='container-fluid'>
    <div class='row'>
      <div class='col-lg-12'>
        <h1>Bookstore</h1>
        <%= render partial: 'layouts/nav' %>
        <%= yield %>
      </div>
    </div>
  </div>
</body>
</html>